# Generated by Django 5.2.1 on 2025-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('ML', 'Mandalay'), ('YG', 'Yangon'), ('NP', 'Naypyidaw'), ('MG', 'Magway'), ('SH', 'Shan')], max_length=2)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('major', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('BA', 'Business Administration'), ('EDU', 'Education'), ('ENG', 'Engineering')], max_length=5)),
            ],
        ),
    ]
