# Generated by Django 5.2.1 on 2025-06-05 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nrc',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='NRC must be in the format 14/YGN(N)260328', regex='^\\d{2}/[A-Z]{3}\\(N\\)\\d{6}$')]),
        ),
    ]
