# Generated by Django 5.2.1 on 2025-06-06 14:10

import data.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_student_nrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathername',
            field=models.CharField(default='Unknow', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nrc',
            field=models.CharField(default=data.models.generate_default_nrc, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='NRC must be in the format 14/YGN(N)260328', regex='^\\d{2}/[A-Z]{3}\\(N\\)\\d{6}$')]),
        ),
    ]
