# Generated by Django 5.2.1 on 2025-06-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_student_fathername_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='student',
            name='fathername',
            field=models.CharField(default='', max_length=100),
        ),
    ]
