# Generated by Django 5.2.1 on 2025-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_student_major_alter_student_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('', '---- Select Your Major ----'), ('CS', 'Computer Science'), ('IT', 'Information Technology'), ('BA', 'Business Administration'), ('EDU', 'Education'), ('ENG', 'Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('', '----Select Your State ----'), ('ML', 'Mandalay'), ('YG', 'Yangon'), ('NP', 'Naypyidaw'), ('MG', 'Magway'), ('SH', 'Shan')], max_length=50),
        ),
    ]
